name: gestion_parrainages
description: Application mobile de gestion des parrainages.

# Contraintes SDK CORRIGÉES
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0       
  provider: ^6.1.1   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
