"""Ajout des modèles

Revision ID: ad59150d1703
Revises: 
Create Date: 2025-02-14 10:37:25.416816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad59150d1703'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electeur',
    sa.Column('numElecteur', sa.String(length=20), nullable=False),
    sa.Column('numCIN', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('dateNaissance', sa.Date(), nullable=False),
    sa.Column('lieuNaissance', sa.String(length=100), nullable=False),
    sa.Column('sexe', sa.Enum('M', 'F', name='sexe_enum'), nullable=False),
    sa.Column('bureauVote', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('numElecteur')
    )
    op.create_index(op.f('ix_electeur_numCIN'), 'electeur', ['numCIN'], unique=True)
    op.create_table('periode_parrainage',
    sa.Column('idPeriode', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dateDebut', sa.Date(), nullable=False),
    sa.Column('dateFin', sa.Date(), nullable=False),
    sa.Column('etat', sa.Enum('OUVERT', 'FERMÉ', name='etat_periode_enum'), nullable=False),
    sa.PrimaryKeyConstraint('idPeriode')
    )
    op.create_table('candidat',
    sa.Column('numElecteur', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('partiPolitique', sa.String(length=100), nullable=True),
    sa.Column('slogan', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('couleur1', sa.String(length=10), nullable=True),
    sa.Column('couleur2', sa.String(length=10), nullable=True),
    sa.Column('couleur3', sa.String(length=10), nullable=True),
    sa.Column('urlInfo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['numElecteur'], ['electeur.numElecteur'], ),
    sa.PrimaryKeyConstraint('numElecteur'),
    sa.UniqueConstraint('telephone')
    )
    op.create_index(op.f('ix_candidat_email'), 'candidat', ['email'], unique=True)
    op.create_table('fichier_electoral',
    sa.Column('idFichier', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('dateUpload', sa.DateTime(), nullable=False),
    sa.Column('idMembre', sa.Integer(), nullable=False),
    sa.Column('etatValidation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idMembre'], ['membre_dge.idMembre'], ),
    sa.PrimaryKeyConstraint('idFichier')
    )
    op.create_table('parrain',
    sa.Column('numElecteur', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('codeAuthentification', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['numElecteur'], ['electeur.numElecteur'], ),
    sa.PrimaryKeyConstraint('numElecteur'),
    sa.UniqueConstraint('telephone')
    )
    op.create_index(op.f('ix_parrain_email'), 'parrain', ['email'], unique=True)
    op.create_table('code_auth',
    sa.Column('idCode', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numParrain', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('dateEnvoi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['numParrain'], ['parrain.numElecteur'], ),
    sa.PrimaryKeyConstraint('idCode')
    )
    op.create_table('parrainage',
    sa.Column('idParrainage', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numElecteur', sa.String(length=20), nullable=False),
    sa.Column('numCandidat', sa.String(length=20), nullable=False),
    sa.Column('codeValidation', sa.String(length=6), nullable=False),
    sa.Column('dateParrainage', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['numCandidat'], ['candidat.numElecteur'], ),
    sa.ForeignKeyConstraint(['numElecteur'], ['parrain.numElecteur'], ),
    sa.PrimaryKeyConstraint('idParrainage')
    )
    op.create_table('tentative_upload',
    sa.Column('idTentative', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idFichier', sa.Integer(), nullable=False),
    sa.Column('dateTentative', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('clefUtilisee', sa.String(length=64), nullable=False),
    sa.Column('resultat', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idFichier'], ['fichier_electoral.idFichier'], ),
    sa.PrimaryKeyConstraint('idTentative')
    )
    op.create_table('validation_fichier',
    sa.Column('idValidation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idFichier', sa.Integer(), nullable=False),
    sa.Column('dateValidation', sa.DateTime(), nullable=False),
    sa.Column('resultat', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['idFichier'], ['fichier_electoral.idFichier'], ),
    sa.PrimaryKeyConstraint('idValidation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_fichier')
    op.drop_table('tentative_upload')
    op.drop_table('parrainage')
    op.drop_table('code_auth')
    op.drop_index(op.f('ix_parrain_email'), table_name='parrain')
    op.drop_table('parrain')
    op.drop_table('fichier_electoral')
    op.drop_index(op.f('ix_candidat_email'), table_name='candidat')
    op.drop_table('candidat')
    op.drop_table('periode_parrainage')
    op.drop_index(op.f('ix_electeur_numCIN'), table_name='electeur')
    op.drop_table('electeur')
    # ### end Alembic commands ###
